version: "3"

services:
  ingestor:
    image: tdmproject/dpc_ingestor
    command: ["--hdfs", "hdfs://namenode:8020", "--tdmq", "http://web:8000"]
    environment:
      NAMENODE_HOSTNAME: namenode


