version: "3"

services:
  temperature_ingestor:
    user: 1000:1000
    image: tdmproject/dpc_ingestor
    environment:
      - NAMENODE_HOSTNAME=namenode
    depends_on:
    - "namenode"
    - "timescaledb"
    command: ["-u", "http://web:8000", "temperature"]

  radar_ingestor:
    user: 1000:1000
    image: tdmproject/dpc_ingestor
    environment:
      - NAMENODE_HOSTNAME=namenode
    depends_on:
    - "namenode"
    - "timescaledb"
    command: ["-u", "http://web:8000", "radar"]

