language: python

python: 3.6

cache: pip

services: docker

before_install:
  - pip install 'flake8>=3.6'
  - flake8 . || true  # We don't fail a build for a flake8 complaint

install:
  - make images

script:
 # sometimes `make start` fails due to services no being ready. We ignore failures at this
 # stage because `make run-tests` will check again
 - make start  || true
 - make run-tests
 - make stop

after_success: .travis/push-images
