language: python

python: 3.6

cache: pip

services: docker

before_install:
  - pip install 'flake8>=3.6'
  - flake8 . || true

install:
  - make images

script:
 # sometimes `make start` fails due to services no being ready. We ignore failures at this
 # stage because `make run-tests` will check again
 - make start  || true
 - echo sleep 20 #  Sleep a few seconds to try to make sure HDFS is ready
 - make run-tests
 - make stop
