language: python

python: 3.6

cache: pip

services: docker

before_install:
  - pip install 'flake8>=3.6'
  - flake8 . || true

install:
  - make images

script:
 - make start
 - sleep 20 #  Sleep a few seconds to try to make sure HDFS is ready
 - make run-tests
 - make stop
