name: CI Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master
      - develop

env:
  TERM: xterm
  # enable Docker push only if the required secrets are defined
  DOCKER_SECRETS_AVAILABLE: ${{ secrets.DOCKERHUB_USER != null && secrets.DOCKERHUB_TOKEN != null }}
  CRS4_HARBOR_SECRETS_AVAILABLE: ${{ secrets.CRS4_HARBOR_USER != null && secrets.CRS4_HARBOR_TOKEN != null }}
  CRS4_REGISTRY: harbor.crs4.it
  DO_PUSH: ${{ github.event_name == 'push' &&
               (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') }}
jobs:
  # Verifies pep8, pyflakes and circular complexity
  flake8:
    name: Check Flake8 (python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install flake8
        run: pip install flake8
      - name: Run checks
        run: flake8 -v tdmq tests

  tests:
    name: Build, Test and Push Docker image
    runs-on: ubuntu-latest
    needs: [flake8]
    defaults:
      run:
        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: print github stuff
        run: |
          echo github.event_name=${{github.event_name}}
          echo github.ref=${{github.ref}}
          echo GITHUB_REF_NAME=${GITHUB_REF_NAME}
          echo ENV_GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}
      - name: Compute build number -- offset by old TravisCI build number
        env:
          BASE_BUILD_NUM: ${{ github.run_number }}
        run: |
          echo "BUILD_NUM=$(($BASE_BUILD_NUM+500))" >> $GITHUB_ENV
      - name: Compute tag and other metadata
        run: |
          echo "ImageTag=${GITHUB_REF_NAME}-${BUILD_NUM}" >> $GITHUB_ENV
          echo "ImageOwner=tdmproject" >> $GITHUB_ENV
          echo "Images=tdmq-client-conda tdmq-client tdmq tdmqj tdmq-db" >> $GITHUB_ENV
      - name: Pull old images
        #  We pull old images to prime the image build process
        #  (expecting pulling to be faster than compiling)
        run: |
          set -o nounset; set -o errexit
          for image in ${Images}; do
            ImageSlug="${ImageOwner}/${image}"
            docker pull ${CRS4_REGISTRY}/${ImageSlug}:latest || true
          done
      - name: Build Docker images
        run: |
          make images
      - name: Start testing services
        run: |
          make start
      - name: Run tests
        run: |
          make run-tests
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.DO_PUSH == 'true' && env.DOCKER_SECRETS_AVAILABLE == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag and push images to Docker Hub
        if: env.DO_PUSH == 'true' && env.DOCKER_SECRETS_AVAILABLE == 'true'
        run: |
          set -o nounset; set -o errexit
          for image in ${Images}; do
            # ImageSlug used here must match the image tag set by the
            # docker build command in the Makefile
            ImageSlug="${ImageOwner}/${image}"

            echo "=== Tagging ${ImageSlug} as ${ImageTag} and latest ==="
            docker tag "${ImageSlug}" "${ImageSlug}:${ImageTag}"
            docker tag "${ImageSlug}" "${ImageSlug}:latest"

            echo "=== Pushing ${ImageSlug}:${ImageTag} and ${ImageSlug}:latest to DockerHub ==="
            docker push "${ImageSlug}:${ImageTag}"
            docker push "${ImageSlug}:latest"
          done
      - name: Login to CRS4 Harbor
        uses: docker/login-action@v1
        if: env.DO_PUSH == 'true' && env.CRS4_HARBOR_SECRETS_AVAILABLE == 'true'
        with:
          registry: ${{ env.CRS4_REGISTRY }}
          username: ${{ secrets.CRS4_HARBOR_USER }}
          password: ${{ secrets.CRS4_HARBOR_TOKEN }}
      - name: Tag and push images
        if: env.DO_PUSH == 'true' && env.CRS4_HARBOR_SECRETS_AVAILABLE == 'true'
        run: |
          set -o nounset; set -o errexit
          for image in ${Images}; do
            # ImageSlug used here must match the image tag set by the
            # docker build command in the Makefile
            ImageSlug="${ImageOwner}/${image}"
            FullImageSlug="${CRS4_REGISTRY}/${ImageSlug}"

            echo "=== Tagging ${ImageSlug} as ${ImageTag} and latest ==="
            docker tag "${ImageSlug}" "${FullImageSlug}:${ImageTag}"
            docker tag "${ImageSlug}" "${FullImageSlug}:latest"

            echo "=== Pushing ${FullImageSlug}:${ImageTag} and ${FullImageSlug}:latest to CRS4 Harbor ==="
            docker push "${FullImageSlug}:${ImageTag}"
            docker push "${FullImageSlug}:latest"
          done
      - name: Clean up working environment
        run: make clean
